In [7]:
import pandas as pd
import numpy as np

# Load datasets
cards = pd.read_csv("Bank_data.csv")
customers = pd.read_csv("customer_expense_dataset_1500.csv")

# Preview
print(cards.head())
#print(customers.head())

  Bank_Name                  Card_Name  Annual_Fee  \
0     ICICI  platinum ship credit card           0
1     ICICI      Amazon pay icici card           0
2     ICICI          Coral Credit Card         500
3      IDFC                  Millennia           0
4      IDFC              First Classic           0

   Grocery_Cashback(%) [Zepto, BigBasket, etc.]  Travel_Cashback(%)  \
0                                           1.5                 2.0
1                                           3.0                 5.0
2                                           5.0                10.0
3                                           1.0                 0.0
4                                           0.0                 0.0

   Dining_Cashback [Swiggy, Zomato, etc.](%) Min_Income_Required(Yearly)  \
0                                       15.0                      300000
1                                        3.0                      300000
2                                       20.0                      500000
3                                        0.0                      300000
4                                        0.0                      500000

  Limit(montly)  Grocery Discount  Travel_Discount  Dining_Discount  \
0         60000                 1                8               15
1        100000                 3                5               10
2         80000                 5               10               20
3        125000                 0                0                0
4        150000                 0                0                0

   Rewards Points  Review InPoints(out of 5) CardType  Lounge access per year  \
0            0.02                        4.5   credit                     0.0
1            0.00                        4.0   credit                     0.0
2            0.02                        4.0   credit                     2.0
3          150.00                        1.5   credit                     5.0
4            3.00                        2.5   credit                     6.0

   Total Cashback(%)
0               18.5
1               11.0
2               35.0
3                1.0
4                0.0

In [8]:
# Rename columns for easier access
cards = cards.rename(columns={
    'Grocery_Cashback(%) [Zepto, BigBasket, etc.]':'grocery_cb',
    'Travel_Cashback(%)':'travel_cb',
    'Dining_Cashback [Swiggy, Zomato, etc.](%)':'dining_cb',
    'Min_Income_Required(Yearly)':'min_income',
    'Limit(montly)':'credit_limit'
})

# Fill missing values
cards.fillna(0, inplace=True)
customers.fillna(0, inplace=True)

# Check data
print(cards.info())
print(customers.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Bank_Name                  78 non-null     object
 1   Card_Name                  78 non-null     object
 2   Annual_Fee                 78 non-null     int64
 3   grocery_cb                 78 non-null     float64
 4   travel_cb                  78 non-null     float64
 5   dining_cb                  78 non-null     float64
 6   min_income                 78 non-null     object
 7   credit_limit               78 non-null     object
 8   Grocery Discount           78 non-null     int64
 9   Travel_Discount            78 non-null     int64
 10  Dining_Discount            78 non-null     int64
 11  Rewards Points             78 non-null     float64
 12  Review InPoints(out of 5)  78 non-null     float64
 13  CardType                   78 non-null     object
 14  Lounge access per year     78 non-null     float64
 15  Total Cashback(%)          78 non-null     float64
dtypes: float64(7), int64(4), object(5)
memory usage: 9.9+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              1500 non-null   object
 1   Grocery           1500 non-null   int64
 2   Travelling        1500 non-null   int64
 3   Electricity       1500 non-null   int64
 4   Internet          1500 non-null   int64
 5   EMI               1500 non-null   int64
 6   Dining            1500 non-null   int64
 7   Entertainment     1500 non-null   int64
 8   OTT               1500 non-null   int64
 9   Ecommerce         1500 non-null   int64
 10  UPI_Transactions  1500 non-null   int64
 11  total Income      1500 non-null   int64
dtypes: int64(11), object(1)
memory usage: 140.8+ KB
None

In [9]:
#Best Credit Card for Grocery Shoppers

best_grocery_card = cards.sort_values(by="grocery_cb", ascending=False)

print(best_grocery_card[['Bank_Name','Card_Name','grocery_cb']].head())

         Bank_Name                    Card_Name  grocery_cb
27  Bank of Baroda            IRCTC Credit Card        10.0
28  Bank of Baroda            Prime Credit Card        10.0
26  Bank of Baroda             HPCL Credit Card        10.0
44       Axis Bank  Axis Bank Value+ Debit Card         5.0
2            ICICI            Coral Credit Card         5.0

In [10]:
#Cards with No Annual Fee

no_fee_cards = cards[cards['Annual_Fee'] == 0]

print(no_fee_cards[['Bank_Name','Card_Name','Annual_Fee']])

              Bank_Name                              Card_Name  Annual_Fee
0                 ICICI              platinum ship credit card           0
1                 ICICI                  Amazon pay icici card           0
3                  IDFC                              Millennia           0
4                  IDFC                          First Classic           0
6                  IDFC                           First Select           0
8                  IDFC                           Republic Day           0
11                  PNB                         Global Classic           0
13                  PNB                        Patanjali RuPay           0
28       Bank of Baroda                      Prime Credit Card           0
29          Canara Bank               VISA Classic Credit Card           0
30          Canara Bank                    MasterCard Standard           0
31          Canara Bank             RuPay Platinum Credit Card           0
33          Canara Bank                       RuPay Debit Card           0
34          Canara Bank                        VISA Debit Card           0
35          Canara Bank                  MasterCard Debit Card           0
36          Canara Bank                    EMV Chip Debit Card           0
43            Axis Bank           Axis Bank Delight Debit Card           0
44            Axis Bank            Axis Bank Value+ Debit Card           0
45            Axis Bank  Axis Bank Titanium Rewards Debit Card           0
46            Axis Bank          Axis Bank Platinum Debit Card           0
55            HDFC Bank                       Classic Platinum           0
56            HDFC Bank                         Platinum Debit           0
57            HDFC Bank                     Preferred Platinum           0
61            HDFC Bank                          Vishesh Debit           0
63         Federal Bank                           Visa Celesta           0
64         Federal Bank                           Visa Imperio           0
65         Federal Bank                            Visa Signet           0
66         Federal Bank                     Mastercard Celesta           0
67         Federal Bank                     Mastercard Imperio           0
68         Federal Bank                      Mastercard Signet           0
69         Federal Bank                           Rupay Signet           0
70         Federal Bank                             Rupay Wave           0
77  Kotak Mahindra Bank            Kotak UPI RuPay Credit Card           0

In [11]:
#Match Cards Based on Customer Income


cards['min_income'] = pd.to_numeric(cards['min_income'], errors='coerce')

def eligible_cards(customer_income):
    eligible = cards[cards['min_income'] <= customer_income]
    return eligible[['Bank_Name','Card_Name','min_income']]

print(eligible_cards(400000))

              Bank_Name                              Card_Name  min_income
0                 ICICI              platinum ship credit card    300000.0
1                 ICICI                  Amazon pay icici card    300000.0
3                  IDFC                              Millennia    300000.0
7                  IDFC                                    Ace    300000.0
8                  IDFC                           Republic Day    200000.0
10                  PNB                            Global Gold    350000.0
11                  PNB                         Global Classic    250000.0
12                  PNB                             Millennial    300000.0
13                  PNB                        Patanjali RuPay    100000.0
14                  PNB                           RuPay Select         0.0
15                IDBI                IDBI Delight Credit Card    240000.0
18                  SBI                      Cashback SBI Card    300000.0
19                  SBI                   SimplyCLICK SBI Card    240000.0
23                  SBI                IRCTC SBI Card Platinum    240000.0
24                  SBI    SBI Global International Debit Card         0.0
25                  SBI  SBI Platinum International Debit Card         0.0
28       Bank of Baroda                      Prime Credit Card     15000.0
29          Canara Bank               VISA Classic Credit Card    150000.0
30          Canara Bank                    MasterCard Standard    150000.0
31          Canara Bank             RuPay Platinum Credit Card    200000.0
32          Canara Bank                Canara Gold Credit Card    300000.0
33          Canara Bank                       RuPay Debit Card         0.0
34          Canara Bank                        VISA Debit Card         0.0
35          Canara Bank                  MasterCard Debit Card         0.0
36          Canara Bank                    EMV Chip Debit Card         0.0
37            Axis Bank              Axis Bank ACE Credit Card    400000.0
40            Axis Bank           Airtel Axis Bank Credit Card    350000.0
41            Axis Bank         Flipkart Axis Bank Credit Card    350000.0
42            Axis Bank           Axis Bank MyZone Credit Card    300000.0
43            Axis Bank           Axis Bank Delight Debit Card         0.0
44            Axis Bank            Axis Bank Value+ Debit Card         0.0
45            Axis Bank  Axis Bank Titanium Rewards Debit Card         0.0
46            Axis Bank          Axis Bank Platinum Debit Card         0.0
47            HDFC Bank                             Milllennia      1000.0
48            HDFC Bank                                 Swiggy      1500.0
49            HDFC Bank                         Moneyback plus      1000.0
50            HDFC Bank                                Freedom      1000.0
51            HDFC Bank                             Regaligold      2000.0
52            HDFC Bank                  Diners Club Privilege      2000.0
53            HDFC Bank                Diners Club Black Metal      5000.0
54            HDFC Bank                          Infinia Metal      5000.0
55            HDFC Bank                       Classic Platinum         0.0
56            HDFC Bank                         Platinum Debit         0.0
57            HDFC Bank                     Preferred Platinum         0.0
58            HDFC Bank                        Millennia Debit         0.0
59            HDFC Bank                        MoneyBack Debit         0.0
60            HDFC Bank                          Rewards Debit         0.0
61            HDFC Bank                          Vishesh Debit         0.0
62            HDFC Bank                          Giga Business         0.0
65         Federal Bank                            Visa Signet    300000.0
68         Federal Bank                      Mastercard Signet    300000.0
69         Federal Bank                           Rupay Signet    300000.0
70         Federal Bank                             Rupay Wave    400000.0
71  Kotak Mahindra Bank            League Platinum Credit Card    300000.0
72  Kotak Mahindra Bank            Kotak Cashback+ Credit Card    300000.0
73  Kotak Mahindra Bank            IndianOil Kotak Credit Card    250000.0
75  Kotak Mahindra Bank                  Kotak Air Credit Card    400000.0
76  Kotak Mahindra Bank             PVR INOX Kotak Credit Card    250000.0
77  Kotak Mahindra Bank            Kotak UPI RuPay Credit Card    250000.0

In [14]:
#Calculate Total Cashback for a Customer

def calculate_cashback(customer):

    grocery = customer['Grocery']
    travel = customer['Travelling']
    dining = customer['Dining']

    cashback = cards.copy()

    cashback['Grocery_CB_Value'] = grocery * cashback['grocery_cb']/100
    cashback['Travel_CB_Value'] = travel * cashback['travel_cb']/100
    cashback['Dining_CB_Value'] = dining * cashback['dining_cb']/100

    cashback['Total_Cashback'] = (
        cashback['Grocery_CB_Value'] +
        cashback['Travel_CB_Value'] +
        cashback['Dining_CB_Value']
    )

    return cashback[['Bank_Name','Card_Name','Total_Cashback']].sort_values(
        by='Total_Cashback', ascending=False
    )


customer = customers.iloc[0]
print(calculate_cashback(customer).head())

         Bank_Name                 Card_Name  Total_Cashback
27  Bank of Baroda         IRCTC Credit Card          1094.5
28  Bank of Baroda         Prime Credit Card          1094.5
26  Bank of Baroda          HPCL Credit Card          1094.5
2            ICICI         Coral Credit Card           775.2
15           IDBI   IDBI Delight Credit Card           751.9

In [15]:
#Best Dining Cashback Cards

best_dining = cards.sort_values(by="dining_cb", ascending=False)

print(best_dining[['Bank_Name','Card_Name','dining_cb']].head())

    Bank_Name                     Card_Name  dining_cb
43  Axis Bank  Axis Bank Delight Debit Card       25.0
2       ICICI             Coral Credit Card       20.0
0       ICICI     platinum ship credit card       15.0
15      IDBI       IDBI Delight Credit Card       15.0
16      IDBI          Royale Signature card       15.0

In [16]:
#Annual Fee vs Cashback Comparison

cashback = calculate_cashback(customers.iloc[0])

comparison = cashback.merge(cards[['Card_Name','Annual_Fee']], on="Card_Name")

comparison['Net_Value'] = comparison['Total_Cashback'] - comparison['Annual_Fee']

print(comparison.sort_values(by="Net_Value", ascending=False).head())

         Bank_Name              Card_Name  Total_Cashback  Annual_Fee  \
1   Bank of Baroda      Prime Credit Card         1094.50         0.0
2   Bank of Baroda       HPCL Credit Card         1094.50       499.0
0   Bank of Baroda      IRCTC Credit Card         1094.50       500.0
12             PNB         Global Classic          397.88         0.0
13           ICICI  Amazon pay icici card          369.28         0.0

    Net_Value
1     1094.50
2      595.50
0      594.50
12     397.88
13     369.28

In [18]:
#Filter Cards by Credit Limit

cards['credit_limit'] = pd.to_numeric(cards['credit_limit'], errors='coerce')

cards[cards['credit_limit'] >= 50000][['Bank_Name','Card_Name','credit_limit']]

              Bank_Name                    Card_Name  credit_limit
0                 ICICI    platinum ship credit card       60000.0
1                 ICICI        Amazon pay icici card      100000.0
2                 ICICI            Coral Credit Card       80000.0
3                  IDFC                    Millennia      125000.0
4                  IDFC                First Classic      150000.0
..                  ...                          ...           ...
73  Kotak Mahindra Bank  IndianOil Kotak Credit Card      300000.0
74  Kotak Mahindra Bank    Zen Signature Credit Card      600000.0
75  Kotak Mahindra Bank        Kotak Air Credit Card      500000.0
76  Kotak Mahindra Bank   PVR INOX Kotak Credit Card      200000.0
77  Kotak Mahindra Bank  Kotak UPI RuPay Credit Card      300000.0

[70 rows x 3 columns]

In [19]:
#Highest Reward Points Cards

cards.sort_values(by="Rewards Points", ascending=False)[
    ['Bank_Name','Card_Name','Rewards Points']
].head()

    Bank_Name                  Card_Name  Rewards Points
38  Axis Bank  Axis Bank Neo Credit Card           200.0
13        PNB            Patanjali RuPay           150.0
3        IDFC                  Millennia           150.0
9         PNB            Global Platinum           150.0
10        PNB                Global Gold           100.0

In [20]:
#Cards with Lounge Access

lounge_cards = cards[cards['Lounge access per year'] > 0]

print(lounge_cards[['Bank_Name','Card_Name','Lounge access per year']])

              Bank_Name                              Card_Name  \
2                 ICICI                      Coral Credit Card
3                  IDFC                              Millennia
4                  IDFC                          First Classic
5                  IDFC                            WOW ! Black
6                  IDFC                           First Select
8                  IDFC                           Republic Day
9                   PNB                        Global Platinum
10                  PNB                            Global Gold
12                  PNB                             Millennial
16                IDBI                   Royale Signature card
18                  SBI                      Cashback SBI Card
21                  SBI                         SBI Card Prime
22                  SBI                         SBI Card ELITE
25                  SBI  SBI Platinum International Debit Card
26       Bank of Baroda                       HPCL Credit Card
27       Bank of Baroda                      IRCTC Credit Card
29          Canara Bank               VISA Classic Credit Card
30          Canara Bank                    MasterCard Standard
31          Canara Bank             RuPay Platinum Credit Card
32          Canara Bank                Canara Gold Credit Card
33          Canara Bank                       RuPay Debit Card
34          Canara Bank                        VISA Debit Card
35          Canara Bank                  MasterCard Debit Card
36          Canara Bank                    EMV Chip Debit Card
37            Axis Bank              Axis Bank ACE Credit Card
40            Axis Bank           Airtel Axis Bank Credit Card
41            Axis Bank         Flipkart Axis Bank Credit Card
42            Axis Bank           Axis Bank MyZone Credit Card
43            Axis Bank           Axis Bank Delight Debit Card
55            HDFC Bank                       Classic Platinum
56            HDFC Bank                         Platinum Debit
57            HDFC Bank                     Preferred Platinum
58            HDFC Bank                        Millennia Debit
61            HDFC Bank                          Vishesh Debit
62            HDFC Bank                          Giga Business
63         Federal Bank                           Visa Celesta
64         Federal Bank                           Visa Imperio
65         Federal Bank                            Visa Signet
66         Federal Bank                     Mastercard Celesta
67         Federal Bank                     Mastercard Imperio
68         Federal Bank                      Mastercard Signet
69         Federal Bank                           Rupay Signet
70         Federal Bank                             Rupay Wave
74  Kotak Mahindra Bank              Zen Signature Credit Card
75  Kotak Mahindra Bank                  Kotak Air Credit Card

    Lounge access per year
2                      2.0
3                      5.0
4                      6.0
5                      4.0
6                      6.0
8                      4.0
9                      8.0
10                     2.0
12                     2.0
16                     4.0
18                     4.0
21                    12.0
22                    14.0
25                     4.0
26                     4.0
27                     4.0
29                     2.0
30                     2.0
31                     5.0
32                     5.0
33                     2.0
34                     2.0
35                     2.0
36                     2.0
37                     4.0
40                     4.0
41                     4.0
42                     4.0
43                     4.0
55                     8.0
56                     8.0
57                     8.0
58                     4.0
61                     8.0
62                     4.0
63                     2.0
64                     6.0
65                     2.0
66                     2.0
67                     6.0
68                     2.0
69                     1.0
70                     1.0
74                     2.0
75                     4.0

In [21]:
#Customer Specific Credit Card Recommendation

def recommend_card(customer):

    result = calculate_cashback(customer)
    eligible = cards[cards['min_income'] <= customer['total Income']]
    result = result[result['Card_Name'].isin(eligible['Card_Name'])]
    return result.head(5)

print(recommend_card(customers.iloc[10]))

         Bank_Name                     Card_Name  Total_Cashback
28  Bank of Baroda             Prime Credit Card         1847.10
48       HDFC Bank                        Swiggy         1159.84
13             PNB               Patanjali RuPay          826.31
44       Axis Bank   Axis Bank Value+ Debit Card          739.50
43       Axis Bank  Axis Bank Delight Debit Card          682.75